export const CATEGORY_HIERARCHY = {
  "art-department": [
    "Art Dept Assistant",
    "Art Dept Co Ordinator",
    "Art Dept Runner",
    "Art Director",
    "Clearance Co Ord",
    "Graphic Artist",
    "Model Maker",
    "Production Designer",
    "Props Buyer",
    "Props Maker",
    "Props Master",
    "Sculptor",
    "Set Decorator",
    "Set Dresser",
    "Standby Assist",
    "Standby Props",
    "Supervising Art Director",
  ],
  "assistant-director": [
    "1st Assistant Director",
    "2nd Assistant Director",
    "3rd Assistant Director",
    "Additional Ad",
    "Tvc 2nd",
  ],
  camera: [
    "1st Assistant Camera",
    "2nd Assistant Camera",
    "Aerials",
    "Camera Operator",
    "Camera Owner Op",
    "Cinematographer",
    "Data Wrangler",
    "Digital Imaging Tech",
    "Documentary",
    "Drones",
    "Gimbal",
    "Motion Control",
    "Phantom Operator",
    "Qtake",
    "Remote Head Operator",
    "Remote Head Technician",
    "Ronin 4d",
    "Steadicam",
    "Stills Photographer",
    "Trinity Operator",
    "Video Van",
    "Videosplit Playback",
  ],
  casting: [
    "Casting Assist",
    "Casting Consultant",
    "Casting Director",
    "Extras Casting",
  ],
  catering: ["Caterers"],
  "child-welfare": ["Chaperone", "Child Wrangler"],
  costume: [
    "Costume Buyer",
    "Costume Co Ord",
    "Costume Designer",
    "Costume Makers",
    "Costume Standby",
    "Costume Supervisor",
    "Stylists",
    "Tvc Wardrobe",
    "Wardrobe Assistant",
  ],
  director: ["Director", "Director Dop", "Directors Assistant"],
  electrics: [
    "Additional Drama Elex",
    "Gaffer",
    "Lighting Assistant",
    "Lighting Board Op",
    "Riggers Elex",
    "Rigging Gaffer",
  ],
  "food-stylists": ["Food Stylist"],
  graduates: [
    "Graduate Art Department",
    "Graduate Assistant Director",
    "Graduate Camera",
    "Graduate Costume",
    "Graduate Director",
    "Graduate Electrics",
    "Graduate Grips",
    "Graduate Hair And Makeup",
    "Graduate Location",
    "Graduate Post Production",
    "Graduate Production",
    "Graduate Script Supervisor",
    "Graduate Sound",
    "Graduate Spfx",
    "Graduate Unit",
    "Graduate Virtual Reality",
  ],
  grips: [
    "Additional Drama Grip",
    "Dolly Grip",
    "Grip Assistant",
    "Jib Operators",
    "Key Grip",
    "Remote Head Technician Grip",
    "Riggersgrips",
    "Scorpio Crane Tech",
    "Swing Tech",
    "Techno Crane",
    "Tracking Veh Driver",
    "Tracking Vehicles",
  ],
  hair: ["Hair Assistant", "Hairdresser"],
  location: [
    "Location Co Ord",
    "Location Manager",
    "Location Scouts Assistant",
    "On Set Location",
    "Security",
    "Traffic Control",
    "Traffic Management",
  ],
  makeup: [
    "Drama Additional",
    "Hod Hairmakeup",
    "Makeup Artist",
    "Makeup Assistant",
    "Prosthetics",
  ],
  medical: [
    "1st Aid Certificate",
    "Covid Co Ord",
    "Midwife",
    "Paramedic",
    "Set Nurse",
  ],
  "post-production": ["Editors", "Post Production Supervisor"],
  production: [
    "Assistant Co Ord",
    "Drama Line Producer",
    "Drama Production Co Ord",
    "Drama Production Manager",
    "Driver",
    "Field Prod Fixer",
    "Prod Dir Personal Assistant",
    "Researchers",
    "Script Co Ordinator",
  ],
  "script-supervisor": ["Script Supervisor"],
  sound: ["Boom Operator", "Sound Recordist"],
  spfx: ["Spfx Co Ordinator", "Spfx Supervisor"],
  storyboards: ["Concept Artist", "Storyboard Artist"],
  sustainability: ["Sustainability Co Ords"],
  transport: ["Swing Captain", "Transport Co Ord", "Transport Manager"],
  underwater: [
    "Diving Certificate",
    "Underwater Camera",
    "Underwater Electrics",
    "Underwater Grip",
  ],
  unit: [
    "Greenroom Bus",
    "Makeup Bus",
    "Makeup Wardrobe Bus",
    "Portable Toilets",
    "Production Bus",
    "Unit Assistant",
    "Unit Manager",
    "Wardrobe Bus",
  ],
  "vehicle-support": [
    "Vehicle Co Ordinators",
    "Vehicle Supervisor",
    "Vehicle Transport",
  ],
  "visual-fx": [
    "Visual Fx Co Ordinator",
    "Visual Fx Prod Mgr",
    "Visual Fx Supervisor",
  ],
  writer: ["Writer"],
};
